---
- hosts: all
  gather_facts: false
  tasks:
    - name: Install CLT if required
      ansible.builtin.script: install_clt.sh
      changed_when: false

- hosts: all
  roles:
    - geerlingguy.mac.homebrew

- hosts: all
  tasks:
    - name: brew paths.d
      become: yes
      ansible.builtin.copy:
        dest: /etc/paths.d/brew
        content: /opt/homebrew/bin
        owner: root
        group: wheel
        mode: 0644

    - name: Tap cask-versions
      community.general.homebrew_tap:
        name: homebrew/cask-versions

    - name: install brew packages
      community.general.homebrew:
        update_homebrew: true
        formula:
          - node
          - htop
          - tree
          - tmux
          - ansible
          - mas

    - name: Install GitUp
      community.general.homebrew_cask:
        name: gitup
        state: present

    - name: Install Battery
      community.general.homebrew_cask:
        name: battery
        state: present

    - name: Install Maccy
      community.general.homebrew_cask:
        name: maccy
        state: present

    - name: Install MonitorControl
      community.general.homebrew_cask:
        name: monitorcontrol
        state: present

    - name: Install Mac App Store applications
      community.general.mas:
        state: present
        id:
          - 2121813704 # CleanMyKeyboard

    - name: OhMyZsh
      ansible.builtin.git:
        repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
        depth: 1
        dest: /Users/Shared/.oh-my-zsh

    - name: .zshrc
      ansible.builtin.copy:
        src: zshrc.sh
        dest: /Users/{{ ansible_user }}/.zshrc
        owner: "{{ ansible_user }}"
        group: staff
        mode: 0640

    - name: Configure Defaults
      ansible.builtin.script: defaults.sh
      changed_when: false
